import pandas as pd
import numpy as np
import streamlit as st
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import datetime

# Load and process the data from Excel
def load_data(file_path):
    data = pd.read_excel(file_path, sheet_name='Population')
    return data

# Initialize metadata
def initialize_metadata():
    metadata = {
        'Generated By': os.getlogin(),
        'PC Name': os.environ.get("COMPUTERNAME", "Unknown"),
        'Date and Time': datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'Threshold Used': threshold,
        'Company Name': company_name,
        'Year-End': year_end,
        'Account Name': account_name
    }
    return metadata

# Sampling logic
def execute_sampling(data, threshold):
    key_items = data[data['Item Value'] > threshold]
    excluding_key_items = data[data['Item Value'] <= threshold]
    key_items_total = key_items['Item Value'].sum()
    population_total = data['Item Value'].sum()
    key_item_percentage = (key_items_total / population_total) * 100
    return key_items, excluding_key_items, key_items_total, population_total, key_item_percentage

# Create the report (Key Items and Population Excluding Key Items)
def create_report(key_items, excluding_key_items):
    key_items_report = key_items[['Item Number', 'Item Value', 'Description', 'Date']]
    excluding_key_items_report = excluding_key_items[['Item Number', 'Item Value', 'Description', 'Date']]
    return key_items_report, excluding_key_items_report

# Email report function (for sending via SMTP)
def send_email_report(to_email, key_item_count, key_items_total, key_items_percentage, keep_pdf=False):
    sender_email = "your_email@example.com"
    password = "your_password"
    subject = "Key Items Sampling Report"
    body = f"Dear Team,\n\nPlease find attached the Key Items Sampling Report.\n\nTotal Key Items: {key_item_count}\nTotal Key Items Value: {key_items_total}\nPercentage of Population: {key_items_percentage}%\n\nBest Regards,\nYour Company"

    # Email body
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    # SMTP server connection
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        text = msg.as_string()
        server.sendmail(sender_email, to_email, text)
        server.quit()
        st.success("Email sent successfully!")
    except Exception as e:
        st.error(f"Failed to send email: {str(e)}")

# Main Streamlit UI
def app():
    st.title("Key Items Sampling Tool")

    # Upload Excel file
    uploaded_file = st.file_uploader("Upload your Excel file", type=["xlsx"])
    if uploaded_file:
        df = load_data(uploaded_file)
        st.write("Data loaded successfully.")

        # Get threshold value, company name, etc. (These would typically come from the Excel file)
        threshold = st.number_input("Enter the threshold value", min_value=0.0, value=1000.0)
        company_name = st.text_input("Company Name", "Sample Company")
        year_end = st.date_input("Year End", datetime.date(2025, 12, 31))
        account_name = st.text_input("Account Name", "Account 123")

        # Execute Sampling logic
        if st.button("Run Sampling"):
            key_items, excluding_key_items, key_items_total, population_total, key_items_percentage = execute_sampling(df, threshold)

            # Create the report
            key_items_report, excluding_key_items_report = create_report(key_items, excluding_key_items)

            # Display the results
            st.subheader("Key Items Report")
            st.write(key_items_report)

            st.subheader("Population Excluding Key Items Report")
            st.write(excluding_key_items_report)

            st.subheader("Summary")
            st.write(f"Total Key Items Value: {key_items_total}")
            st.write(f"Percentage of Population: {key_items_percentage:.2f}%")

            # Ask if they want to save PDF
            save_pdf = st.radio("Save as PDF?", ("Yes", "No"))

            if save_pdf == "Yes":
                # Logic to save the PDF (you can use `reportlab` or other libraries for PDF generation)
                pdf_path = "path/to/save/report.pdf"
                st.success(f"PDF saved at: {pdf_path}")
            
            # Send email report
            send_email_report("recipient@example.com", len(key_items), key_items_total, key_items_percentage, save_pdf == "Yes")

if __name__ == "__main__":
    app()
